[server]
enableStaticServing = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
showErrorDetails = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#212529"
font = "sans serif"

[client]
caching = true
allowRunOnSave = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true